# Generated by Django 4.1 on 2022-10-21 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auth_rating", models.FloatField(default=0.0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_category", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_post",
                    models.CharField(
                        choices=[("AR", "статья"), ("NE", "новость")],
                        default="AR",
                        max_length=2,
                    ),
                ),
                ("date_time_post", models.DateTimeField(auto_now_add=True)),
                ("title_post", models.CharField(max_length=250)),
                ("text_post", models.TextField()),
                ("rating_post", models.FloatField(default=0.0)),
                (
                    "author_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="NewsApp.author"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NewsApp.category",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="NewsApp.post"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="categories_post",
            field=models.ManyToManyField(
                through="NewsApp.PostCategory", to="NewsApp.category"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_comment", models.TextField()),
                ("data_time_comment", models.DateTimeField(auto_now_add=True)),
                ("rating_comment", models.FloatField(default=0.0)),
                (
                    "post_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="NewsApp.post"
                    ),
                ),
                (
                    "user_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
